ALTER TABLE file_descriptor DROP COLUMN description;

ALTER TABLE file_descriptor
ADD COLUMN meta_1 VARCHAR(150),
ADD COLUMN meta_2 VARCHAR(150),
ADD COLUMN meta_3 INT REFERENCES CODE_STORE_ITEM(id),
ADD COLUMN note VARCHAR(150);