CREATE TABLE GOOGLE_DRIVE_FILE (
	id SERIAL PRIMARY KEY,
	tenant_id INT NOT NULL REFERENCES TENANT(id),
	file_id INTEGER NOT NULL REFERENCES file_descriptor(id) UNIQUE,
	priority INT NOT NULL,
	web_view_url VARCHAR(150) NOT NULL,
	google_drive_id VARCHAR(100),
	anyone_with_link BOOLEAN,
	status INT NOT NULL REFERENCES CODE_STORE_ITEM(id),
	created_by INTEGER NOT NULL REFERENCES AUTH_USER(id),
	created_on TIMESTAMP NOT NULL,
	modified_by INTEGER NOT NULL REFERENCES AUTH_USER(id),
	modified_on TIMESTAMP NOT NULL
);

CREATE INDEX ON GOOGLE_DRIVE_FILE (tenant_id);
